# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'json-viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.find_box = QtWidgets.QLineEdit(self.centralwidget)
        self.find_box.setObjectName("find_box")
        self.horizontalLayout.addWidget(self.find_box)
        self.find_button = QtWidgets.QPushButton(self.centralwidget)
        self.find_button.setObjectName("find_button")
        self.horizontalLayout.addWidget(self.find_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox.setObjectName("gbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tree_widget = QtWidgets.QTreeWidget(self.gbox)
        self.tree_widget.setColumnCount(1)
        self.tree_widget.setObjectName("tree_widget")
        self.tree_widget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.tree_widget)
        self.verticalLayout.addWidget(self.gbox)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.find_button.clicked.connect(self.find_button.click) # type: ignore
        self.find_box.returnPressed.connect(self.find_button.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.find_button.setText(_translate("MainWindow", "Find"))
        self.gbox.setTitle(_translate("MainWindow", "GroupBox"))
